apiVersion: v1
entries:
  fail-manytimes:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-10-25T16:09:21.31968+08:00"
    description: A Helm chart for Kubernetes
    digest: edf4e7cb5d64ea6adad4cd9f600542acd2351315c39a4e0baff4a21703a275dc
    name: fail-manytimes
    type: application
    urls:
    - https://poyiya.github.io/charts/fail-manytimes-0.0.1.tgz
    version: 0.0.1
  gpu-hog:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-10-25T16:09:21.31994+08:00"
    description: A Helm chart to produce non-stopping pytorch workloads that saturate
      GPUs
    digest: 208e2239bb25606e54cd9a7383ed3387769d3bf13edded70d01c6a8fc3564e59
    name: gpu-hog
    urls:
    - https://poyiya.github.io/charts/gpu-hog-0.1.0.tgz
    version: 0.1.0
  tdcsqa-auto-nginx:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-10-25T16:09:21.320842+08:00"
    description: A Helm chart for Kubernetes
    digest: 9bf850c3e371718221b5ceb526a9b0bb8a781db3914f39666255e9a7271f2f25
    name: tdcsqa-auto-nginx
    urls:
    - https://poyiya.github.io/charts/tdcsqa-auto-nginx-0.0.1.tgz
    version: 0.0.1
  vectoradd-app:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-10-25T16:09:21.321908+08:00"
    description: A Helm chart to exercise GPUs
    digest: 1950ef0a89c12b6fc50b0aee97bfd2c3d23a194e3bccd003d03b4addf37aebcb
    name: vectoradd-app
    urls:
    - https://poyiya.github.io/charts/vectoradd-app-0.2.0.tgz
    version: 0.2.0
  wrong-image-name:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-10-25T16:09:21.324373+08:00"
    description: A Helm chart for Kubernetes
    digest: dbec994ff118f12ffc430d9d0a5ddded30d31709db7673cf7424797da1ccc0bb
    name: wrong-image-name
    type: application
    urls:
    - https://poyiya.github.io/charts/wrong-image-name-0.1.0.tgz
    version: 0.1.0
generated: "2021-10-25T16:09:21.317327+08:00"
