apiVersion: v1
entries:
  fail-manytimes:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-04-20T14:22:41.100956+08:00"
    description: A Helm chart for Kubernetes
    digest: edf4e7cb5d64ea6adad4cd9f600542acd2351315c39a4e0baff4a21703a275dc
    name: fail-manytimes
    type: application
    urls:
    - https://poyiya.github.io/charts/fail-manytimes-0.0.1.tgz
    version: 0.0.1
  gpu-hog:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-04-20T14:22:41.101676+08:00"
    description: A Helm chart to produce non-stopping gpu workload
    digest: 4658f5ffdf4d8a1a7dcd47a8fff3954d061739a9beadd5e3b3f819f55d74e96c
    name: gpu-hog
    urls:
    - https://poyiya.github.io/charts/gpu-hog-0.1.0.tgz
    version: 0.1.0
  tdcsqa-auto-nginx:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2021-04-20T14:22:41.101871+08:00"
    description: A Helm chart for Kubernetes
    digest: 9bf850c3e371718221b5ceb526a9b0bb8a781db3914f39666255e9a7271f2f25
    name: tdcsqa-auto-nginx
    urls:
    - https://poyiya.github.io/charts/tdcsqa-auto-nginx-0.0.1.tgz
    version: 0.0.1
  wrong-image-name:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2021-04-20T14:22:41.102613+08:00"
    description: A Helm chart for Kubernetes
    digest: dbec994ff118f12ffc430d9d0a5ddded30d31709db7673cf7424797da1ccc0bb
    name: wrong-image-name
    type: application
    urls:
    - https://poyiya.github.io/charts/wrong-image-name-0.1.0.tgz
    version: 0.1.0
generated: "2021-04-20T14:22:41.099687+08:00"
